import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { NextUIProvider } from '@gameblog/ui'
import './_styles/index.scss'
import { Header } from '@widgets/Header'
import { Footer } from '@widgets/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      className='dark'
      lang='en'
    >
      <NextUIProvider>
        <body className={inter.className}>
          <div className='layoutComponent'>
            <Header />
            <div className='w-full bg-transparent py-5 md:px-5'>
              <div className='w-full rounded-xl bg-[var(--body-bg-color)] p-5 shadow-md'>
                {children}
              </div>
            </div>
            <Footer />
          </div>
        </body>
      </NextUIProvider>
    </html>
  )
}
