export const SECRET_JWT_ACCESS = 'SECRET_JWT_ACCESS'
export const SECRET_JWT_REFRESH = 'SECRET_JWT_REFRESH'

export const REFRESH_TOKEN_COOKIE = 'refreshToken'
export const MAX_AGE_COOKIE_REFRESH = 15 * 24 * 60 * 60 * 1000